#!/bin/bash

# TabzChrome Dev Script
# Starts backend in tmux with optional logs window

set -e

# Force consistent terminal type regardless of parent terminal
export TERM=xterm-256color
unset WT_SESSION
unset WT_PROFILE_ID

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$SCRIPT_DIR/../backend"

SESSION_NAME="tabz-chrome"

echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  TabzChrome Dev Script                ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
echo ""

# Interactive configuration
echo -e "${YELLOW}📋 Configuration:${NC}"
echo ""

# Ask about logs window
read -p "$(echo -e ${BLUE}Enable live logs window? ${NC}${YELLOW}[y/N]${NC}: )" ENABLE_LOGS
ENABLE_LOGS=${ENABLE_LOGS:-n}

# Ask about log level (consola levels)
echo ""
echo -e "${BLUE}Select log level:${NC}"
echo -e "  ${YELLOW}0${NC} - Silent (no logs)"
echo -e "  ${YELLOW}1${NC} - Errors only"
echo -e "  ${YELLOW}2${NC} - Warnings and errors"
echo -e "  ${YELLOW}3${NC} - Info (default, recommended)"
echo -e "  ${YELLOW}4${NC} - Debug (verbose)"
echo -e "  ${YELLOW}5${NC} - Trace (very verbose)"
echo ""
read -p "$(echo -e ${BLUE}Log level ${NC}${YELLOW}[0-5, default: 3]${NC}: )" LOG_LEVEL
LOG_LEVEL=${LOG_LEVEL:-3}

# Validate log level
if ! [[ "$LOG_LEVEL" =~ ^[0-5]$ ]]; then
  echo -e "${YELLOW}⚠️  Invalid log level, using 3 (info)${NC}"
  LOG_LEVEL=3
fi

# Write .env file with selected log level
cat > "$BACKEND_DIR/.env" << EOF
# TabzChrome Backend Configuration
# Generated by scripts/dev.sh

# Logging Configuration (consola levels)
# 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=trace
LOG_LEVEL=$LOG_LEVEL
EOF

echo ""
echo -e "${GREEN}✓ Configuration saved${NC}"
echo ""

# Check if tmux is installed
if ! command -v tmux &> /dev/null; then
    echo -e "${RED}❌ tmux is not installed. Please install it first:${NC}"
    echo -e "   ${YELLOW}sudo apt install tmux${NC}"
    exit 1
fi

# Kill existing session if it exists
if tmux has-session -t $SESSION_NAME 2>/dev/null; then
    echo -e "${YELLOW}⚠️  Existing session found. Killing it...${NC}"
    tmux kill-session -t $SESSION_NAME
fi

# Check if backend dependencies are installed
if [ ! -d "$BACKEND_DIR/node_modules" ]; then
    echo -e "${YELLOW}📦 Installing backend dependencies...${NC}"
    cd "$BACKEND_DIR"
    npm install
fi

echo -e "${GREEN}🚀 Creating tmux session: $SESSION_NAME${NC}"
echo ""

# Create new tmux session with backend in first window
tmux new-session -d -s $SESSION_NAME -n backend -c "$BACKEND_DIR"
tmux send-keys -t $SESSION_NAME:backend "npm start" C-m

# Create logs window if enabled
if [[ "$ENABLE_LOGS" =~ ^[Yy]$ ]]; then
  tmux new-window -t $SESSION_NAME -n logs -c "$SCRIPT_DIR"
  tmux send-keys -t $SESSION_NAME:logs "echo 'Backend Logs (updating every 1s) - Ctrl+C to stop'; sleep 1; while true; do clear; tmux capture-pane -t $SESSION_NAME:backend -p -S -100; sleep 1; done" C-m
fi

# Select the backend window
tmux select-window -t $SESSION_NAME:backend

echo -e "${GREEN}✅ TabzChrome backend started in tmux session!${NC}"
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Tmux Commands:${NC}"
echo -e "  Attach:  ${YELLOW}tmux attach -t $SESSION_NAME${NC}"
echo -e "  Detach:  ${YELLOW}Ctrl+B, then D${NC}"
if [[ "$ENABLE_LOGS" =~ ^[Yy]$ ]]; then
  echo -e "  Windows: ${YELLOW}Ctrl+B, then 0/1${NC} (backend/logs)"
else
  echo -e "  Windows: ${YELLOW}Ctrl+B, then 0${NC} (backend)"
fi
echo -e "  Kill:    ${YELLOW}tmux kill-session -t $SESSION_NAME${NC}"
echo ""
echo -e "${BLUE}URLs:${NC}"
echo -e "  Backend:  ${YELLOW}http://localhost:8129${NC}"
echo ""
echo -e "${BLUE}Log Level: ${YELLOW}$LOG_LEVEL${NC} ${NC}(0=silent, 1=fatal, 2=error, 3=warn, 4=info, 5=debug)"
if [[ "$ENABLE_LOGS" =~ ^[Yy]$ ]]; then
  echo -e "${BLUE}Live Logs: ${GREEN}Enabled${NC}"
else
  echo -e "${BLUE}Live Logs: ${YELLOW}Disabled${NC} (logs visible in backend window)"
fi
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}Claude can capture logs:${NC}"
echo -e "  ${YELLOW}tmux capture-pane -t $SESSION_NAME:backend -p -S -100${NC}"
echo ""
echo -e "${YELLOW}Attaching to tmux session...${NC}"
echo ""

# Attach to the session
tmux attach -t $SESSION_NAME
